/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserImterface;

import Materials.Materials2;
import static Materials.Materials2.MaterialsLoan;
import java.util.ArrayList;

/**
 *
 * @author Monserrath
 */
public class Handback extends javax.swing.JFrame {

    /**
     * Creates new form Handback
     */
    public Handback() {
        initComponents();
    }
    
    public ArrayList handBack(String idS){
        ArrayList fillComboB = new ArrayList();
        fillComboB = MaterialsLoan.get(idS);
        System.out.println(fillComboB.get(0));
        return fillComboB;
    }
    
    public boolean checkExistance(String idS){
        return MaterialsLoan.containsKey(idS);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_handback_studentID = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txt_handback_studentID1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_handback_studentID2 = new javax.swing.JTextField();
        btn_handback_returnBook = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_handback_return = new javax.swing.JButton();
        btn_handback_searchStudent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel1.setText("Student ID:");

        txt_handback_studentID.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        txt_handback_studentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_handback_studentIDActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel2.setText("Fee:");

        txt_handback_studentID1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        txt_handback_studentID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_handback_studentID1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel3.setText("Days Past Due:");

        txt_handback_studentID2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        txt_handback_studentID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_handback_studentID2ActionPerformed(evt);
            }
        });

        btn_handback_returnBook.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        btn_handback_returnBook.setText("Return Book");

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel4.setText("Handback Item");

        btn_handback_return.setText("Return");
        btn_handback_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_handback_returnActionPerformed(evt);
            }
        });

        btn_handback_searchStudent.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        btn_handback_searchStudent.setText("Search Student");
        btn_handback_searchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_handback_searchStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_handback_studentID, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_handback_searchStudent))))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_handback_studentID2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_handback_returnBook)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txt_handback_studentID1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_handback_return)
                    .addComponent(jLabel4)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_handback_studentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_handback_searchStudent))
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_handback_studentID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_handback_studentID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btn_handback_returnBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btn_handback_return)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_handback_studentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_handback_studentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_handback_studentIDActionPerformed

    private void txt_handback_studentID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_handback_studentID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_handback_studentID1ActionPerformed

    private void txt_handback_studentID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_handback_studentID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_handback_studentID2ActionPerformed

    private void btn_handback_searchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_handback_searchStudentActionPerformed
        // TODO add your handling code here:
        
        String idS = txt_handback_studentID.getText();
        if(checkExistance(idS) == true){
            ArrayList populate = new ArrayList();
            populate = handBack(idS);
            for (int i = 0; i > populate.size(); i++ ){
                jComboBox1.addItem("Holi");
            }
        }
        
    }//GEN-LAST:event_btn_handback_searchStudentActionPerformed

    private void btn_handback_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_handback_returnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
    }//GEN-LAST:event_btn_handback_returnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Handback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Handback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Handback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Handback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Handback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_handback_return;
    private javax.swing.JButton btn_handback_returnBook;
    private javax.swing.JButton btn_handback_searchStudent;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_handback_studentID;
    private javax.swing.JTextField txt_handback_studentID1;
    private javax.swing.JTextField txt_handback_studentID2;
    // End of variables declaration//GEN-END:variables
}
