/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserImterface;

import Materials.Materials2;
import Students.Student;
import static Materials.Materials2.MaterialsLoan;
import static Students.Student.hashStudents;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Monserrath
 */
public class Handback extends javax.swing.JFrame {

    /**
     * Creates new form Handback
     */
    public Handback() {
        initComponents();
    }
    
    public ArrayList handBack(String idS){
        ArrayList fillComboB = new ArrayList();
        fillComboB = MaterialsLoan.get(idS);
        System.out.println(fillComboB.get(1));
        return fillComboB;
    }
    
    public boolean checkExistance(String idS){
        return MaterialsLoan.containsKey(idS);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_handback_studentID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_handback_studenFee = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_handback_studentPD = new javax.swing.JTextField();
        btn_handback_returnBook = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_handback_return = new javax.swing.JButton();
        btn_handback_searchStudent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel1.setText("Student ID:");

        txt_handback_studentID.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        txt_handback_studentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_handback_studentIDActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel2.setText("Fee:");

        txt_handback_studenFee.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        txt_handback_studenFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_handback_studenFeeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel3.setText("Days Past Due:");

        txt_handback_studentPD.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        txt_handback_studentPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_handback_studentPDActionPerformed(evt);
            }
        });

        btn_handback_returnBook.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        btn_handback_returnBook.setText("Return Book");
        btn_handback_returnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_handback_returnBookActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel4.setText("Handback Item");

        btn_handback_return.setText("Return");
        btn_handback_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_handback_returnActionPerformed(evt);
            }
        });

        btn_handback_searchStudent.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        btn_handback_searchStudent.setText("Search Student");
        btn_handback_searchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_handback_searchStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_handback_return)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_handback_studentID, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_handback_searchStudent))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txt_handback_studenFee, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_handback_returnBook))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_handback_studentPD, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_handback_studentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_handback_searchStudent))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_handback_studentPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_handback_studenFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_handback_returnBook))
                .addGap(44, 44, 44)
                .addComponent(btn_handback_return)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_handback_studentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_handback_studentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_handback_studentIDActionPerformed

    private void txt_handback_studenFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_handback_studenFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_handback_studenFeeActionPerformed

    private void txt_handback_studentPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_handback_studentPDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_handback_studentPDActionPerformed

    private void btn_handback_searchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_handback_searchStudentActionPerformed
        // TODO add your handling code here:
        String idS = txt_handback_studentID.getText();
        if(checkExistance(idS) == false || idS.equals("")){
            JOptionPane.showMessageDialog(this, "The Student ID is wrong");
            txt_handback_studenFee.setEnabled(false);
            txt_handback_studentPD.setEditable(false);
        }
        else{
            txt_handback_studenFee.setEnabled(true);
            txt_handback_studentPD.setEditable(true);
        }
    }//GEN-LAST:event_btn_handback_searchStudentActionPerformed

    private void btn_handback_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_handback_returnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
    }//GEN-LAST:event_btn_handback_returnActionPerformed

    private void btn_handback_returnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_handback_returnBookActionPerformed
        ArrayList temp = new ArrayList(handBack(txt_handback_studentID.getText()));
        int lendDays = Integer.parseInt((String) temp.get(1));
        if (txt_handback_studentPD.equals("") == false){
            int multi = (Integer.parseInt(txt_handback_studentPD.getText())) * 300;
            txt_handback_studenFee.setText(Integer.toString(multi));
            MaterialsLoan.remove(txt_handback_studentID.getText());
            temp = hashStudents.get(txt_handback_studentID.getText());
            temp.set(2, multi);
            hashStudents.put(txt_handback_studentID.getText(), temp);
            txt_handback_studentPD.setText("");
            txt_handback_studentID.setText("");
            txt_handback_studenFee.setText("");
            JOptionPane.showMessageDialog(this, "The item have been returned");
        }
        else{
            JOptionPane.showMessageDialog(this, "There is an empty space");
        }
    }//GEN-LAST:event_btn_handback_returnBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Handback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Handback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Handback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Handback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Handback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_handback_return;
    private javax.swing.JButton btn_handback_returnBook;
    private javax.swing.JButton btn_handback_searchStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_handback_studenFee;
    private javax.swing.JTextField txt_handback_studentID;
    private javax.swing.JTextField txt_handback_studentPD;
    // End of variables declaration//GEN-END:variables
}
